name: "codspeed"
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  codspeed:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon run :build

      - name: Run benchmarks
        # use version from `main` branch to always test the latest version, in real projects, use a tag, like `@v1`
        uses: CodSpeedHQ/action@feat/introspection-exit-code
        env:
          CODSPEED_DEBUG: true
        with:
          upload_url: ${{ secrets.CODSPEED_UPLOAD_URL_ADRIEN_LOCAL }}/upload
          run: |
            pnpm --filter vitest-runner bench
